Repository getinapp/appetizer, pull requests merged in 2022-04, with the labels that each got.

#19 [FEATURE] - Create Select component
  .github/workflows/lint-and-test.yml
  package.json
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/index.tsx
  src/components/Select/styles.ts
  src/index.ts
  yarn.lock
Labels: enhancement, minor

#27 [BUGFIX] - Input label position
  src/components/Input/index.tsx
  src/styles/global.ts
Labels: patch

#28 fix(globalstyles): modal styles
  src/styles/global.ts
Labels: bug, patch
